server:
  port: 8080
spring:
  application:
    name: tool-center
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tool_center
    username: postgres
    password: mysecretpassword
    hikari:
      minimum-idle: 5 # 最小空闲连接数
      maximum-pool-size: 200 # 最大连接池大小
      idle-timeout: 30000 # 空闲连接的最大存活时间（毫秒）
      pool-name: SpringBootJPAHikariCP # 连接池名称
      max-lifetime: 1800000 # 连接的最大存活时间（毫秒）
      connection-timeout: 30000 # 获取连接的最大等待时间（毫秒）
      leak-detection-threshold: 2000 # 泄漏检测的阈值（毫秒）
security:
  basic:
    enabled: true
# knife4j配置
knife4j:
  enable: true
  openapi:
    title: "工具众筹平台"
    description: "工具众筹"
    version: v1.0
    group:
      task:
        group-name: tool-center
        api-rule: package
        api-rule-resources:
          - com.github.jiquanzhong.toolcenter.controller
