server:
  port: 8080
spring:
  application:
    name: tool-center
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tool_center
    username: postgres
    password: mysecretpassword